### ISSUE TITLE
Script fails to run with a empty "fan1_input"

### ISSUE THREAD

**Issue by axipher** [BoukeHaarsma23/WattmanGTK#11]
I have a water-cooled RX 480 so there is no fan plugged in to the GPU's fan header.  This means that it never gets a return value.  You will have to add some sort of error checking on that field for sure, and potentially the others instead of just assuming they are going to return something.

My quick fix was just changing "fan1_input" to "pwm1" in all the files so trick it into just reading a value that does work.

```
axipher@CANARY:/sys/class/drm/card0/device/hwmon/hwmon3$ cat fan1_input 
cat: fan1_input: Invalid argument
```

**Comment by BoukeHaarsma23** [comment]
I will work on something that ignores certain sensors if they are unavailable.

**Comment by BoukeHaarsma23** [comment]
Please check if the empty sensor branch fixes your problem

**Comment by Haxk20** [comment]
There is no GPU fan in laptops with AMD GPU as it seems but empty-sensor branch fixes it.

**Comment by ibrokemypie** [comment]
similar issue on my vega 56, not sure why it would be the case as it does indeed have a fan.
```
Traceback (most recent call last):
  File "./wattman.py", line 82, in <module>
    GPU = GPU(cards[int(cardnr)], linux_kernelmain, linux_kernelsub)
  File "/opt/wattman-gtk/GPU.py", line 19, in __init__
    self.get_currents()
  File "/opt/wattman-gtk/GPU.py", line 90, in get_currents
    self.fan_speed = self.read_sensor("/hwmon/hwmon0/subsystem/hwmon0/fan1_input")
  File "/opt/wattman-gtk/GPU.py", line 65, in read_sensor
    with open(self.cardpath+filename) as origin_file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/hwmon/hwmon0/subsystem/hwmon0/fan1_input'
```

**Comment by BoukeHaarsma23** [comment]
@ibrokemypie @axipher please check if you still have this issue after 14e7de6d5708885716756bc744592cb6e444cb2d

**Comment by axipher** [comment]
> 
> 
> @ibrokemypie @axipher please check if you still have this issue after [14e7de6](https://github.com/BoukeHaarsma23/WattmanGTK/commit/14e7de6d5708885716756bc744592cb6e444cb2d)

Will check tonight, currently no remote access to that Linux machine, much appreciated on the great work on this so far though.

**Comment by axipher** [comment]
So I grabbed the latest and ran setup but you are missing a dependency on your list in the Readme, you need to add 'python3-setuptools'.

It runs properly after that telling me what mask to set (which does produce flickering lines) and I can open WattmanGTK and change all the settings.

I'm not sure what the intended values are for Fan Speed [RPM], but is is ranging from 47 to 52 for me so I'm wondering if that is actually the PWM speed, not the actual reported RPM.

Screenshot: [https://drive.google.com/file/d/1R2gt8Sg4Hqnq-P2Lwy4HAsYvt29LimkP/view?usp=sharing](url)

**Comment by axipher** [comment]
```
axipher@CANARY:/sys/class/hwmon/hwmon3$ ls -al
total 0
drwxr-xr-x 3 root root    0 Nov  7 21:23 .
drwxr-xr-x 3 root root    0 Nov  7 21:23 ..
lrwxrwxrwx 1 root root    0 Nov  7 21:26 device -> ../../../0000:26:00.0
-r--r--r-- 1 root root 4096 Nov  7 21:23 fan1_input
-r--r--r-- 1 root root 4096 Nov  7 21:26 in0_input
-r--r--r-- 1 root root 4096 Nov  7 21:26 in0_label
-r--r--r-- 1 root root 4096 Nov  7 21:23 name
drwxr-xr-x 2 root root    0 Nov  7 21:26 power
-r--r--r-- 1 root root 4096 Nov  7 21:26 power1_average
-rw-r--r-- 1 root root 4096 Nov  7 21:23 power1_cap
-r--r--r-- 1 root root 4096 Nov  7 21:23 power1_cap_max
-r--r--r-- 1 root root 4096 Nov  7 21:23 power1_cap_min
-rw-r--r-- 1 root root 4096 Nov  7 21:26 pwm1
-rw-r--r-- 1 root root 4096 Nov  7 21:26 pwm1_enable
-r--r--r-- 1 root root 4096 Nov  7 21:26 pwm1_max
-r--r--r-- 1 root root 4096 Nov  7 21:26 pwm1_min
lrwxrwxrwx 1 root root    0 Nov  7 21:26 subsystem -> ../../../../../../class/hwmon
-r--r--r-- 1 root root 4096 Nov  7 21:23 temp1_crit
-r--r--r-- 1 root root 4096 Nov  7 21:26 temp1_crit_hyst
-r--r--r-- 1 root root 4096 Nov  7 21:23 temp1_input
-rw-r--r-- 1 root root 4096 Nov  7 21:26 uevent
axipher@CANARY:/sys/class/hwmon/hwmon3$ 

```

**Comment by BoukeHaarsma23** [comment]
51ae135c4de929a9df1b8f4888facd090ab67947 should fix this for you

**Comment by axipher** [comment]
Still similar error to above where it errors on 'fan1_max'.

Should it be looking for 'pwm1_max' instead?

I seem to have fixed it by changing line 94 in 'plot.py' by changing

`GPU.fansensors.read_attribute('_max',True)`

to

`GPU.fanpwmsensors.read_attribute('_max',True)`

**Comment by BoukeHaarsma23** [comment]
You are correct. I need some sleep ;)

**Comment by GloriousEggroll** [comment]
can confirm had same issue, changing that line fixes it.

**Comment by BoukeHaarsma23** [comment]
so is the issue fixed now @axipher ? That way I can close this

**Comment by axipher** [comment]
I believe so yes, I can confirm tonight for you when I get home from work, but that small fix was all that was needed for the program to run and display correctly.
