### ISSUE TITLE
RX 480 has no Power  (%) is greyed out

### ISSUE THREAD

**Issue by axipher** [BoukeHaarsma23/WattmanGTK#12]
The Power (%) button is greyed out so I can't make changes to that.

I'm also not entirely clear what the "Power Limit 150(W) automatic" does versus changing it to manual and sliding it somewhere between 0.0(W) and 150(W).

**Comment by BoukeHaarsma23** [comment]
This is intended behaviour. If you move the power limit switch to manual you can set the slider, while it is disabled when it is set to automatic. The power (%) button is a future feature that I intend to add.
