### ISSUE TITLE
radeon 7950 does not work

### ISSUE THREAD

**Issue by reivanen** [BoukeHaarsma23/WattmanGTK#13]
The program does not work with sapphire 7950 vapor-x.

>Error during reading current states, WattmanGTK will not be able to continue :(
>Please check if "cat /sys/class/drm/card0/device/pp_od_clk_voltage" returns something useful

The card has been running flawlessly using AMDGPU for over a year and even crypto mining works no problem. Only thing that never worked is overclocking core or memory, which is probably related to wattman failing.

**Comment by BoukeHaarsma23** [comment]
Did you set the kernel parameter? See the FAQ

**Comment by reivanen** [comment]
yes, that check comes before this error.

**Comment by BoukeHaarsma23** [comment]
Maybe this is something in the AMDGPU kernel driver for your generation of card then. Will check and report back if I know something.

**Comment by BoukeHaarsma23** [comment]
Please check here: https://bugs.freedesktop.org/show_bug.cgi?id=106306

Do you have the same behaviour?

**Comment by BoukeHaarsma23** [comment]
Please check if you still have this issue after 14e7de6d5708885716756bc744592cb6e444cb2d

**Comment by reivanen** [comment]
> amdgpu card found in /sys/class/hwmon/hwmon2 hwmon folder
> Error during reading current states, WattmanGTK will not be able to continue :(
> Please check if "cat /sys/class/drm/card0/device/pp_od_clk_voltage" returns something useful
> Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
> Traceback (most recent call last):
>   File "/home/varikonniemi/WattmanGTK/WattmanGTK/GPU.py", line 93, in get_states
>     raise FileNotFoundError
> FileNotFoundError
> 
> During handling of the above exception, another exception occurred: ...
I have a clue from the discussion you linked, this card has a OC switch, so maybe the non-oc state uses a bios that is locked.

**Comment by BoukeHaarsma23** [comment]
But does the GUI still crash now?

**Comment by reivanen** [comment]
Now i arrived at this:

> import: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
> ./wattman.py: line 2: syntax error near unexpected token `"Gtk",'
> ./wattman.py: line 2: `gi.require_version("Gtk", "3.0")'

**Comment by BoukeHaarsma23** [comment]
can you post the output of:
`cat /sys/class/drm/card0/device/pp_dpm_sclk`

**Comment by BoukeHaarsma23** [comment]
commit ba8520f3a1a2b8b98011391ba84a2804db9208e0 could resolve your problem

**Comment by reivanen** [comment]
Sadly, no.

> 1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
> 03:00.0 uses amdgpu kernel driver
> Searching for sysfs path...
> /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:08.0/0000:03:00.0 belongs to 03:00.0 with symbolic link to /sys/class/drm/card0/device
> Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:08.0/0000:03:00.0
> amdgpu card found in /sys/class/hwmon/hwmon2 hwmon folder
> Checking which device this hwmon path belongs to
> /sys/class/hwmon/hwmon2 belongs to /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:08.0/0000:03:00.0 (PC Partner Limited / Sapphire Technology Tahiti PRO [Radeon HD 7950/8950 OEM / R9 280])
> Found sensor in0_input
> Trying to read /sys/class/hwmon/hwmon2/in0_input
> Cannot read /sys/class/hwmon/hwmon2/in0_input
> Found sensor temp1_crit
> Trying to read /sys/class/hwmon/hwmon2/temp1_crit
> Found sensor pwm1_enable
> Trying to read /sys/class/hwmon/hwmon2/pwm1_enable
> Found sensor pwm1
> Trying to read /sys/class/hwmon/hwmon2/pwm1
> Found sensor temp1_crit_hyst
> Trying to read /sys/class/hwmon/hwmon2/temp1_crit_hyst
> Found sensor power1_cap_min
> Trying to read /sys/class/hwmon/hwmon2/power1_cap_min
> Found sensor power1_cap
> Trying to read /sys/class/hwmon/hwmon2/power1_cap
> Found sensor pwm1_min
> Trying to read /sys/class/hwmon/hwmon2/pwm1_min
> Found sensor power1_average
> Trying to read /sys/class/hwmon/hwmon2/power1_average
> Cannot read /sys/class/hwmon/hwmon2/power1_average
> Found sensor power1_cap_max
> Trying to read /sys/class/hwmon/hwmon2/power1_cap_max
> Found sensor fan1_input
> Trying to read /sys/class/hwmon/hwmon2/fan1_input
> Found sensor temp1_input
> Trying to read /sys/class/hwmon/hwmon2/temp1_input
> Found sensor pwm1_max
> Trying to read /sys/class/hwmon/hwmon2/pwm1_max
> Found sensor in0_label
> Trying to read /sys/class/hwmon/hwmon2/in0_label
> Cannot read file pp_od_clk_voltage, trying using pp_dpm_sclk and pp_dpm_mclk
> Cannot do seperate overclocking via states, only by percentage!
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/GPU.py", line 108, in get_states
>     raise FileNotFoundError
> FileNotFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/wattmanGTK", line 11, in <module>
>     load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
>   File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/wattman.py", line 125, in main
>     card.get_states()
>   File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/GPU.py", line 127, in get_states
>     self.pstate_clock.append(int(match.group(2)))
> AttributeError: 'NoneType' object has no attribute 'group'
>

**Comment by BoukeHaarsma23** [comment]
It could be that powerplay is not enabled on your device, can you post the output of:
`cat /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:08.0/0000:03:00.0/pp_dpm_sclk`

**Comment by reivanen** [comment]
4.19 and the output is empty.

**Comment by BoukeHaarsma23** [comment]
Yeah, that is the reason why it's failing. This is kernel/hardware related then, not much I can do.
