### ISSUE TITLE
Cannot launch on RX560X

### ISSUE THREAD

**Issue by Haxk20** [BoukeHaarsma23/WattmanGTK#14]
When trying to launch it on Arch linux and 4.19 this error occurs:

Multiple cards found!
Card [0]: /sys/class/drm/card1/device
Card [1]: /sys/class/drm/card0/device
Which card do you want to use Wattman-GTK for (default: 0)? [0-9] 1
Traceback (most recent call last):
  File "./wattman.py", line 82, in <module>
    GPU = GPU(cards[int(cardnr)], linux_kernelmain, linux_kernelsub)
  File "/home/haxk20/WattmanGTK/GPU.py", line 19, in __init__
    self.get_currents()
  File "/home/haxk20/WattmanGTK/GPU.py", line 84, in get_currents
    self.gpu_clock, self.gpu_state = self.get_current_clock("/pp_dpm_sclk")
TypeError: cannot unpack non-iterable NoneType object

Thanks.

**Comment by BoukeHaarsma23** [comment]
What are the contents of the pp_dpm_sclk in this case?

**Comment by Haxk20** [comment]
> What are the contents of the pp_dpm_sclk in this case?

0: 214Mhz 
1: 603Mhz 
2: 958Mhz 
3: 1060Mhz 
4: 1128Mhz 
5: 1182Mhz 
6: 1230Mhz 
7: 1275Mhz

**Comment by BoukeHaarsma23** [comment]
I see, WattmanGTK cannot read your current clockspeed since it needs an asterisk at the current clockspeed. So in my case the pp_dpm_sclk looks like:

> 0: 300Mhz 
> 1: 608Mhz 
> 2: 910Mhz 
> 3: 1077Mhz 
> 4: 1145Mhz 
> 5: 1191Mhz 
> 6: 1236Mhz *
> 7: 1266Mhz 

This is probably a bug in the kernel driver. I will check this

**Comment by Haxk20** [comment]
> I see, WattmanGTK cannot read your current clockspeed since it needs an asterisk at the current clockspeed. So in my case the pp_dpm_sclk looks like:
> 
> > 0: 300Mhz
> > 1: 608Mhz
> > 2: 910Mhz
> > 3: 1077Mhz
> > 4: 1145Mhz
> > 5: 1191Mhz
> > 6: 1236Mhz *
> > 7: 1266Mhz
> 
> This is probably a bug in the kernel driver. I will check this

Just tried setting the performance state to high and wattmanGTK launched. This is because of that "soft wall" in other issue. The driver doesnt seem to report at which speed its running so the driver assumes lowest and so the GPU runs at lowest clock but it seems its not visible even in pp_dpm_sclk. Where can we report this bug ?

**Comment by Haxk20** [comment]
Once i changed the performance state of the GPU from auto to high the pp_dpm_sclk returns:
0: 214Mhz 
1: 603Mhz 
2: 958Mhz 
3: 1060Mhz 
4: 1128Mhz 
5: 1182Mhz 
6: 1230Mhz 
7: 1275Mhz *

**Comment by BoukeHaarsma23** [comment]
Please check if you still have this issue after 14e7de6d5708885716756bc744592cb6e444cb2d

**Comment by BoukeHaarsma23** [comment]
I assume this is fixed now. If not, please let me know. Otherwise, I will close this in a few days.

**Comment by Haxk20** [comment]
> I assume this is fixed now. If not, please let me know. Otherwise, I will close this in a few days.

Yes issue fixed.
