### ISSUE TITLE
Resize top section based opn number of sensors

### ISSUE THREAD

**Issue by axipher** [BoukeHaarsma23/WattmanGTK#24]
As the title says, can you auto resize the top sensor list and graph area based on the number of active sensors so you don't have to stretch it just that tiny bit to see all of them.

**Comment by axipher** [comment]
I'll check it out tonight, thanks.

**Comment by BoukeHaarsma23** [comment]
@axipher All testing on the wattmangtk-next branch is appreciated. A lot has changed there!

**Comment by axipher** [comment]
Seems to launch and run fine as is, the flickering caused by setting the flag is still bothersome though so can't keep that on all the time.  I did notice that the -next branch can no longer run until you set that flag.  The previous master branch would at least open to allow monitoring without that flag set and that was very useful.

**Comment by BoukeHaarsma23** [comment]
> the flag is still bothersome though so can't keep that on all the time.
What flag do you mean?

**Comment by axipher** [comment]
> 
> 
> > the flag is still bothersome though so can't keep that on all the time.
> 
> What flag do you mean?

The Grub bootline flag for enabling overdrive.

**Comment by BoukeHaarsma23** [comment]
dc50d9e4b6f26f4ee9fc1f8b9f5c5b90a3623f8f implements a command line switch you can set. You can use `-o overdrive` the override the overdrive check

**Comment by axipher** [comment]
Awesome, thanks, will update my shortcuts tonight
