### ISSUE TITLE
Update label/description of GPU Power

### ISSUE THREAD

**Issue by axipher** [BoukeHaarsma23/WattmanGTK#25]
It is unclear still what the GPU Power setting actually is/does.  Right now my RX 480 'POWER [W] 'is at '150'.

I can assume that is supposed to be 150% instead which would correlate with +50% power in the Windows version of AMD Overdrive, which would be odd if your slider actually let's you set the 'Power Limit' slider to '0%'.  Should this actually be -50% to +50%?

Screenshot: [https://drive.google.com/file/d/1R2gt8Sg4Hqnq-P2Lwy4HAsYvt29LimkP/view?usp=sharing](url)

**Comment by SethBarberee** [comment]
It means 150 W. AKA the power load on your GPU.

**Comment by BoukeHaarsma23** [comment]
Exactly like @SethBarberee says
