### ISSUE TITLE
Update the graph with a second Y-axis on the right side

### ISSUE THREAD

**Issue by axipher** [BoukeHaarsma23/WattmanGTK#26]
Add a second Y-Axis to the right side of the graph to take care of 'Core Clock', 'Mem Clock' and 'Fan Speed' that would go from 0 to 3000.

Then you can update the y-axis on the left side range from 0 to 150 or something that makes a little more sense.

Alternatively if the current library you are using doesn't allow for multi-scales on one graph, having a second graph in the top section probably wouldn't hurt, keep them at 30 seconds of history, just have each graph take up half the horizontal space it does now.

**Comment by axipher** [comment]
Forget to check on this last night before I passed out, will check tonight on it.

**Comment by BoukeHaarsma23** [comment]
Should be something like this: 
https://i.imgur.com/ahrQrEO.png

**Comment by axipher** [comment]
That should work for now until you figure out what you are doing with multiple cards and whatnot.
