### ISSUE TITLE
WattmanGTK could not find any sensors

### ISSUE THREAD

**Issue by fabrixx** [BoukeHaarsma23/WattmanGTK#29]
Hi.
I'm testing with x86_64 Linux 4.18.16-arch1-1-ARCH 
Radeon R7m265 and receive:

```
[fabrizio@localhost ~]$ wattmanGTK
Multiple cards found!
Card [0]: /sys/class/drm/card1/device
Card [1]: /sys/class/drm/card0/device
Which card do you want to use Wattman-GTK for (default: 0)? [0-9] 1
WattmanGTK could not find any sensors
```

Its possible to test with this card?

**Comment by BoukeHaarsma23** [comment]
Does your graphics card use the AMDGPU driver?

Check
'''lspci -k'''

**Comment by fabrixx** [comment]
Yes

Il giorno gio 8 nov 2018, 21:44 BoukeHaarsma23 <notifications@github.com>
ha scritto:

**Comment by BoukeHaarsma23** [comment]
You could try the AMDGPU detection branch.

**Comment by BoukeHaarsma23** [comment]
So you use the radeon kernel driver instead of the amdgpu kernel driver. This is not supported by WattmanGTK. So as suggested: take a look at the radeon profile project.

https://github.com/marazmista/radeon-profile

**Comment by fabrixx** [comment]
08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI]
Opal XT [Radeon R7 M265/M365X/M465]
Subsystem: Dell Opal XT [Radeon R7 M265/M365X/M465]
Kernel driver in use: radeon
Kernel modules: radeon, amdgpu


Il giorno ven 9 nov 2018 alle ore 20:13 BoukeHaarsma23 <
notifications@github.com> ha scritto:

**Comment by BoukeHaarsma23** [comment]
> Kernel driver in use: radeon 

I don't know how to make this more clear to you.

Try blacklisting radeon and reboot. If you then encounter any issues open a new issue.

**Comment by fabrixx** [comment]
Excuse me I had replied to your message by email when you said to give the command to verify the configuration, then you had edited the answer.

Thanks I understood.

**Comment by fabrixx** [comment]
Ok radeon-profile work.
I blacklisted radeon and re.run wattman this is my output now:

[fabrizio@localhost ~]$ wattmanGTK
2 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
08:00.0 uses amdgpu kernel driver
Searching for sysfs path...
Searching for GPU with string: /sys/devices/pci????:??/????:08:00.0
Searching for GPU with string: /sys/devices/pci????:??/**/????:08:00.0
Sysfs path found in /sys/devices/pci0000:00/0000:00:1c.4/0000:08:00.0
WattmanGTK could not find any sensors
