### ISSUE TITLE
ValueError: Namespace Gtk not available for version 3.0

### ISSUE THREAD

**Issue by Daniele71** [BoukeHaarsma23/WattmanGTK#49]
Hello, on opensuse TW:

> python3 run.py 
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    from WattmanGTK import wattman
  File "/local/WattmanGTK-master/WattmanGTK/wattman.py", line 2, in <module>
    gi.require_version("Gtk", "3.0")
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 131, in require_version
    (namespace, version))
ValueError: Namespace Gtk not available for version 3.0

Wattman downloaded as zip. Do I miss something ?

Thanks,

Daniele.

**Comment by BoukeHaarsma23** [comment]
apologies for the late response. Do you have all requirements installed?

**Comment by BoukeHaarsma23** [comment]
The line you have this error on requires the Python3-gi package. So I would look in that general direction. For me it is unclear how tumbleweed packages this. But a google search gives me the suspicion you need the `python3-gobject` and `python3-gobject-cairo` packages.

**Comment by Daniele71** [comment]
Yes, Python3-gi is packaged as Python3-gobject.
Installed packages (sorry a bit long):

libpython3_6m1_0-32bit-3.6.5-3.3.x86_64
libpython3_6m1_0-3.6.5-3.3.x86_64
python3-3.6.5-3.4.x86_64
python3-apparmor-2.13-6.1.x86_64
python3-appdirs-1.4.3-4.1.noarch
python3-base-3.6.5-3.3.x86_64
python3-bind-9.11.2-42.1.noarch
python3-cairo-1.15.1-1.2.x86_64
python3-cairocffi-0.8.1-1.1.noarch
python3-cffi-1.11.5-4.1.x86_64
python3-cupshelpers-1.5.7-16.3.noarch
python3-curses-3.6.5-3.4.x86_64
python3-Cycler-0.10.0-2.3.noarch
python3-dbm-3.6.5-3.4.x86_64
python3-dbus-python-1.2.8-2.1.x86_64
python3-decorator-4.3.0-1.1.noarch
python3-firewall-0.6.3-1.1.noarch
python3-gobject-3.30.1-1.2.x86_64
python3-gobject-cairo-3.30.1-1.2.x86_64
python3-gobject-Gdk-3.30.1-1.2.x86_64
python3-kiwisolver-1.0.1-2.2.x86_64
python3-matplotlib-3.0.2-1.1.x86_64
python3-matplotlib-cairo-3.0.2-1.1.x86_64
python3-matplotlib-gtk3-3.0.2-1.1.x86_64
python3-numpy-1.15.3-1.1.x86_64
python3-olefile-0.45.1-1.1.noarch
python3-packaging-17.1-1.1.noarch
python3-Pillow-5.3.0-1.1.x86_64
python3-pip-18.1-1.1.noarch
python3-pivy-0.6.4-1.1.x86_64
python3-ply-3.11-3.1.noarch
python3-pycparser-2.19-1.1.noarch
python3-pycups-1.9.73-1.3.x86_64
python3-pycurl-7.43.0.2-5.1.x86_64
python3-pyparsing-2.3.1~test5-1.1.noarch
python3-pyside2-5.11.2-1.1.x86_64
python3-python-dateutil-2.7.3-1.1.noarch
python3-pytz-2018.5-1.1.noarch
python3-qt4-4.12.1-2.5.x86_64
python3-qt5-5.11.3-3.1.x86_64
python3-rpm-4.14.2.1-1.1.x86_64
python3-setuptools-40.5.0-1.1.noarch
python3-sip-4.19.13-1.1.x86_64
python3-six-1.11.0-4.1.noarch
python3-slip-0.6.5-4.2.noarch
python3-slip-dbus-0.6.5-4.2.noarch
python3-solv-0.7.1-1.1.x86_64
python3-speechd-0.8.8-3.2.x86_64
python3-talloc-2.1.14-1.1.x86_64
python3-talloc-32bit-2.1.14-1.1.x86_64
python3-vapoursynth-43-3.5.x86_64
python3-xcffib-0.5.1-1.2.noarch
python3-zypp-plugin-0.6.3-3.1.noarch


Thanks.

**Comment by BoukeHaarsma23** [comment]
Further googling seems to show that you need  `typelib-1_0-Gtk-3_0` , do you have that installed?
