### ISSUE TITLE
Allow voltage control while leaving frequency on auto

### ISSUE THREAD

**Issue by urbenlegend** [BoukeHaarsma23/WattmanGTK#5]
It seems like if I just toggle manual voltage control in GUI and leave frequency on Auto, the voltage values aren't written into the `Set_WattmanGTK_Settings.sh` file. I have to toggle manual for both. In Wattman on Windows, I can just modify the voltage and let the GPU dynamically clock higher or lower depending on temp and power draw. I would like that ability in Linux as well.

If it is not possible to do that in Linux perhaps the GUI should toggle Frequency to manual as well when the user sets Voltage to manual.

**Comment by BoukeHaarsma23** [comment]
Please let me know if 98f79744ceba2ae0c33782129538bd8316d78527 fixed this for you.

**Comment by urbenlegend** [comment]
It writes voltages now but the voltage values are wrong. It seems to be writing the default voltage values instead of my modified voltages.

**Comment by urbenlegend** [comment]
Seems to work now. Thanks!
