### ISSUE TITLE
Wattman on Ryzen2500u

### ISSUE THREAD

**Issue by chris-linux** [BoukeHaarsma23/WattmanGTK#50]
Hi,

many thanks for your tool.
I  just gave it a try on ubuntu 18.04 with kernel 4.19 and an ryzen 2500u based laptop.
The tool starts and i get the following screenshot.

![watmann](https://user-images.githubusercontent.com/5053929/50057391-16ab5880-016a-11e9-9b20-fd33670bcdae.png)

I am not sure if that looks corret, as i can not enable the switches.
Or am i doing something wrong ?

Many thanks !
Christian

**Comment by BoukeHaarsma23** [comment]
APU's do not support P-State overclocking as far as I know. That is why you don't have the ability to change P-states. Hope that answers your question ;)
