### ISSUE TITLE
Kernel 5.0 not supported

### ISSUE THREAD

**Issue by Krteq** [BoukeHaarsma23/WattmanGTK#51]
Hi,

linux kernel 5.0 is considered as unsupported for some reason.

> Unsupported kernel (5.0.0-050000rc1-generic), make sure you are using linux kernel 4.8 or higher.

seems like kernel version check is not counting with version higher than 4.xx

Thx in advance for a fix

**Comment by BoukeHaarsma23** [comment]
Hmm this is strange, I am running on 5.0-rc1 myself as well. Works fine here. Did you compile your own kernel?

**Comment by BoukeHaarsma23** [comment]
I spotted what was wrong in the current master, please check if it works now for you :)

**Comment by Krteq** [comment]
"Issue" fixed with current master now :)

THX
