### ISSUE TITLE
Cannot change voltage on a Vega 64

### ISSUE THREAD

**Issue by breadland** [BoukeHaarsma23/WattmanGTK#52]
Running Kubuntu 18.10 with kernel 4.19.6 and Vega 64 card, wattmanGTK fires up nicely and reads all sensors, as far as I can tell.
However I have trouble getting wattmanGTK to output the powerstate voltages for the gpu and memory I set in wattmanGTK, to the Set_WattmanGTK_Settings.sh file. Those values just won't be written to the file. But the powerlimit-settings is written and works correctly when I runt the Set_WattmanGTK_Settings.sh it self.

So when I run wattmanGTK thru terminal and set everything to where I want and then hit apply, this is what I get in the end:
Traceback (most recent call last):

File "/usr/local/lib/python3.6/dist-packages/WattmanGTK-0.0.1-py3.6.egg/WattmanGTK/handler.py", line 510, in apply

svoltages.append(self.new_state[f"Pstate voltage {i}"])

KeyError: 'Pstate voltage 0'

And this is what's being written to Set_WattmanGTK_Settings.sh:

echo "manual" > /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0/power_dpm_force_performance_level

echo 370000000 > /sys/class/hwmon/hwmon2/power1_cap 

Same thing happens in Arch Linux 4.20 kernel.

And I'm not the only user with this issue. Another one with a Vega 64 has the same exact issue. On Ubuntu 18.04 and the default kernel that comes with it.

Would appreciate any insight into this problem. I heard from somebody that the Vega cards don't have a Pstate voltage 0, so that could be the reason why the script gets stuck at that line.

**Comment by WildPenquin** [comment]
I can confirm this issue.

I believe it's just the script not functioning properly, maybe there is a typo somewhere, but I don't know Python.

**Comment by LeJimster** [comment]
Can confirm this as well, no voltage changes are applied on my Vega 56.  Using Arch 4.20 kernel.

**Comment by BoukeHaarsma23** [comment]
Thanks for letting me now. Sorry that I have been away for a long while. 

I found a typo in creation of the state dictionary. Please let me know if the fix works for you in the dev branch.

**Comment by hyperactivated** [comment]
Vega 64, Arch 4.20 here, dev branch fixes the issue for me.

**Comment by breadland** [comment]
Sorry, I never closed this issue back when the dev branch fixed it. As of now the master branch also has the fix.
