### ISSUE TITLE
overdrive functionality not enabled even though the grub boot parameter is set

### ISSUE THREAD

**Issue by Bednar87** [BoukeHaarsma23/WattmanGTK#64]
Hi,

Running wattmanGTK gives me the following:

> The overdrive functionality seems not enabled on this system.
This means WattmanGTK can not be used.
You could force it by flipping the overdrive bit. For this system it would mean to set amdgpu.ppfeaturemask=0xfffd7fff
Please refer to: https://github.com/BoukeHaarsma23/WattmanGTK#FAQ on how to set this parameter

Now /etc/default/grub:
> GRUB_DEFAULT="Arch Linux Latest"
GRUB_TIMEOUT="5"
GRUB_DISTRIBUTOR="Arch"
GRUB_CMDLINE_LINUX_DEFAULT="quiet amdgpu.ppfeaturemask=0xfffd7fff"
GRUB_CMDLINE_LINUX=""

However,
`printf "0x%08x\n" $(cat /sys/module/amdgpu/parameters/ppfeaturemask)`
yields 0xfffd3fff.

Also:

`readlink -f /sys/class/drm/card0/device/sys/devices`

gives /pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0

Any idea what's going on here? Yes I did update grub. I am on Arch and this is a vega 64 (Gigabyte Gaming OC)

Thanks,

**Comment by Bednar87** [comment]
Ok, I figured it out. It turns out modifying /etc/default/grub only applied to the linux-lts image. I had to add the kernel parameter manually during Boot to the latest kernel's image.

**Comment by raaans** [comment]
> Ok, I figured it out. It turns out modifying /etc/default/grub only applied to the linux-lts image. I had to add the kernel parameter manually during Boot to the latest kernel's image.

I have the exact same problem, could you explain how and what you did exactly?

**Comment by BoBXygene** [comment]
Dont trust Grub customizer, it created me multiple lines of GRUB_CMDLINE_LINUX_DEFAULT in /etc/default/grub
Just kept only one uncommented for the ppfeaturemask to work.
