### ISSUE TITLE
Crash before loading after reading clock states - Vega 64 

### ISSUE THREAD

**Issue by Notakas** [BoukeHaarsma23/WattmanGTK#68]
Hi, I just installed WattmanGTK following the instructions, added the kernel param with the value it recommended me . However, it crashes

`printf "0x%08x\n" $(cat /sys/module/amdgpu/parameters/ppfeaturemask)` returns `0xfffd7fff`, so that should be correct.

This is my `cat /sys/class/drm/card0/device/pp_dpm_sclk` output:
0: 852Mhz *
1: 991Mhz 
2: 1084Mhz 
3: 1138Mhz 
4: 1200Mhz 
5: 1401Mhz 
6: 1536Mhz 
7: 1630Mhz 

And this is the output of WattmanGTK
```
➜  WattmanGTK git:(master) ✗ wattmanGTK

(wattmanGTK:2047): Gtk-WARNING **: 14:00:24.148: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:2047): Gtk-WARNING **: 14:00:24.148: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(wattmanGTK:2047): Gtk-WARNING **: 14:00:24.148: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
03:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0 belongs to 03:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0
amdgpu card found in /sys/class/hwmon/hwmon2 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon2 belongs to /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0 (Advanced Micro Devices, Inc. [AMD/ATI] RX Vega64)
Found sensor freq1_label
Trying to read /sys/class/hwmon/hwmon2/freq1_label
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon2/in0_input
Found sensor fan1_min
Trying to read /sys/class/hwmon/hwmon2/fan1_min
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon2/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon2/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon2/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon2/temp1_crit_hyst
Found sensor power1_cap_min
Trying to read /sys/class/hwmon/hwmon2/power1_cap_min
Found sensor fan1_enable
Trying to read /sys/class/hwmon/hwmon2/fan1_enable
Found sensor fan1_max
Trying to read /sys/class/hwmon/hwmon2/fan1_max
Found sensor freq2_label
Trying to read /sys/class/hwmon/hwmon2/freq2_label
Found sensor power1_cap
Trying to read /sys/class/hwmon/hwmon2/power1_cap
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon2/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon2/power1_average
Found sensor freq1_input
Trying to read /sys/class/hwmon/hwmon2/freq1_input
Found sensor power1_cap_max
Trying to read /sys/class/hwmon/hwmon2/power1_cap_max
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon2/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon2/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon2/pwm1_max
Found sensor fan1_target
Trying to read /sys/class/hwmon/hwmon2/fan1_target
Found sensor freq2_input
Trying to read /sys/class/hwmon/hwmon2/freq2_input
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon2/in0_label
Reading clock states and limits.
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/wattman.py", line 174, in main
    Plot0 = Handler0.init_plot(0, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/handler.py", line 72, in init_plot
    self.plot = Plot(self.builder, self.GPUs, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 58, in __init__
    self.Plotsignals = self.init_signals(self.GPU)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 100, in init_signals
    self.add_available_signal(GPU.sensors, Plotsignals, hwmonpath=GPU.hwmonpath)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 156, in add_available_signal
    self.add_available_signal(value, Plotsignals, hwmonpath=hwmonpath, subsystem=subsystem, stop_recursion = stop_recursion)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 156, in add_available_signal
    self.add_available_signal(value, Plotsignals, hwmonpath=hwmonpath, subsystem=subsystem, stop_recursion = stop_recursion)
  File "/usr/lib/python3.7/site-packages/WattmanGTK-0.0.1-py3.7.egg/WattmanGTK/plot.py", line 151, in add_available_signal
    Plotsignals.append(Plotsignal(signallabel, subsystem_unit_color[subsystem]["unit"],
KeyError: ''
```

Thank you

**Comment by speakn2pabst** [comment]
Hello, I can also reproduce this crash on a Manjaro stable computer.  But while the crash occurs on 5.1 kernel (5.1.8-1) it does not crash on 5.0 kernel (5.0.21-1) and launches normally with the same system.

5.1 kernel output

`wattmanGTK 
1 AMD GPU(s) found. Checking if correct kernel driver is used for this/these.
03:00.0 uses amdgpu kernel driver
Searching for sysfs path...
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0 belongs to 03:00.0 with symbolic link to /sys/class/drm/card0/device
Sysfs path found in /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0
amdgpu card found in /sys/class/hwmon/hwmon1 hwmon folder
Checking which device this hwmon path belongs to
/sys/class/hwmon/hwmon1 belongs to /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0 (ASUSTeK Computer Inc. Vega 10 XL/XT [Radeon RX Vega 56/64])
Found sensor freq1_label
Trying to read /sys/class/hwmon/hwmon1/freq1_label
Found sensor in0_input
Trying to read /sys/class/hwmon/hwmon1/in0_input
Found sensor fan1_min
Trying to read /sys/class/hwmon/hwmon1/fan1_min
Found sensor temp1_crit
Trying to read /sys/class/hwmon/hwmon1/temp1_crit
Found sensor pwm1_enable
Trying to read /sys/class/hwmon/hwmon1/pwm1_enable
Found sensor pwm1
Trying to read /sys/class/hwmon/hwmon1/pwm1
Found sensor temp1_crit_hyst
Trying to read /sys/class/hwmon/hwmon1/temp1_crit_hyst
Found sensor power1_cap_min
Trying to read /sys/class/hwmon/hwmon1/power1_cap_min
Found sensor fan1_enable
Trying to read /sys/class/hwmon/hwmon1/fan1_enable
Found sensor fan1_max
Trying to read /sys/class/hwmon/hwmon1/fan1_max
Found sensor freq2_label
Trying to read /sys/class/hwmon/hwmon1/freq2_label
Found sensor power1_cap
Trying to read /sys/class/hwmon/hwmon1/power1_cap
Found sensor pwm1_min
Trying to read /sys/class/hwmon/hwmon1/pwm1_min
Found sensor power1_average
Trying to read /sys/class/hwmon/hwmon1/power1_average
Found sensor freq1_input
Trying to read /sys/class/hwmon/hwmon1/freq1_input
Found sensor power1_cap_max
Trying to read /sys/class/hwmon/hwmon1/power1_cap_max
Found sensor fan1_input
Trying to read /sys/class/hwmon/hwmon1/fan1_input
Found sensor temp1_input
Trying to read /sys/class/hwmon/hwmon1/temp1_input
Found sensor pwm1_max
Trying to read /sys/class/hwmon/hwmon1/pwm1_max
Found sensor fan1_target
Trying to read /sys/class/hwmon/hwmon1/fan1_target
Found sensor freq2_input
Trying to read /sys/class/hwmon/hwmon1/freq2_input
Found sensor in0_label
Trying to read /sys/class/hwmon/hwmon1/in0_label
Reading clock states and limits.
Traceback (most recent call last):
  File "/usr/bin/wattmanGTK", line 11, in <module>
    load_entry_point('WattmanGTK==0.0.1', 'console_scripts', 'wattmanGTK')()
  File "/usr/lib/python3.7/site-packages/WattmanGTK/wattman.py", line 174, in main
    Plot0 = Handler0.init_plot(0, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/handler.py", line 72, in init_plot
    self.plot = Plot(self.builder, self.GPUs, maxpoints, precision, linux_kernelmain, linux_kernelsub)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 58, in __init__
    self.Plotsignals = self.init_signals(self.GPU)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 100, in init_signals
    self.add_available_signal(GPU.sensors, Plotsignals, hwmonpath=GPU.hwmonpath)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 156, in add_available_signal
    self.add_available_signal(value, Plotsignals, hwmonpath=hwmonpath, subsystem=subsystem, stop_recursion = stop_recursion)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 156, in add_available_signal
    self.add_available_signal(value, Plotsignals, hwmonpath=hwmonpath, subsystem=subsystem, stop_recursion = stop_recursion)
  File "/usr/lib/python3.7/site-packages/WattmanGTK/plot.py", line 151, in add_available_signal
    Plotsignals.append(Plotsignal(signallabel, subsystem_unit_color[subsystem]["unit"],
KeyError: ''`

**Comment by Notakas** [comment]
It's fixed, thanks!
