### ISSUE TITLE
How to automatically overclock at startup

### ISSUE THREAD

**Issue by Gonza21Gd** [BoukeHaarsma23/WattmanGTK#72]
The readme states you can apply a custom profile by a bash script. I had created a profile via the gui but it's lost after reboot. How can I write the profile to a script and apply it automatically at startup?

**Comment by Bengt** [comment]
This question only touches this project. There are many ways to automatically execute arbitrary commands under Linux. An overview:

https://wiki.archlinux.org/index.php/autostarting

You might want to apply the commands listed in the created script at the start of the xserver: 

https://wiki.archlinux.org/index.php/Xprofile

**Comment by rijndael86** [comment]
Yeah. I did not see the Set_WattmanGTK_Settings.sh file, I was asking how to generate some script like that. I've just found it, nvm, thanks :)

**Comment by Bengt** [comment]
Great! I hope, I could help.

Am Sa., 21. Sept. 2019 um 16:27 Uhr schrieb Gonzalo Sanín <
notifications@github.com>:
